\ProvidesClass{utexas-dissertation}[2017/06/12 UTexas Dissertation]

\LoadClassWithOptions{memoir}

% Set Page Geometry
\usepackage[margin=1in,includefoot]{geometry}

% Set Ragged Right
\usepackage{ragged2e}
\RaggedRight

% Set Pagination to bottom/center
\pagestyle{plain}

% Set Footnote Styles
\usepackage{utexas-dissertation-footnotes}

% Global typographic properties (not Font family)
\DoubleSpacing 

% Frontmatter
\usepackage{utexas-dissertation-frontmatter}