\ProvidesClass{utexas-dissertation}[2017/06/12 UTexas Dissertation]

\LoadClassWithOptions{memoir}

% Page styles (Geometry, etc.)
\usepackage{utexas-dissertation-page}

% Pandoc polyfill
\usepackage{pandoc-polyfill}

% Typography
\usepackage{utexas-dissertation-typography}

% Frontmatter
\usepackage{utexas-dissertation-frontmatter}

% Table of Contents
\usepackage{utexas-dissertation-toc}

% Heading Styles
\usepackage{utexas-dissertation-headings}

% Set Footnote Styles
\usepackage{utexas-dissertation-footnotes}